#!/bin/bash

PSOF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${PSOF_DIR}/psof_config $PWD/psof.xml

echo Clean

echo $APPLICATION_LANGUAGE
case $APPLICATION_LANGUAGE in
    "java") 
    BUILD_CMD="mvn clean -f app/pom.xml"
    $BUILD_CMD
    ;;
esac

exit 0;

