#!/bin/bash

PSOF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${PSOF_DIR}/psof_config $PWD/psof.xml

echo Generating sources from DB

#TODO check if we are in correct dir, using psof.xml
mkdir -p $PWD/db/sources/procedure
mysqldump -h ${DB_HOST} -p${DB_PORT} -u${DB_USERNAME} -p${DB_PASSWORD} ${DB_NAME} --routines > $PWD/db/sources/procedure/procedure.sql

mkdir -p $PWD/db/sources/trigger
mysqldump -h ${DB_HOST} -p${DB_PORT} -u${DB_USERNAME} -p${DB_PASSWORD} ${DB_NAME} --triggers > $PWD/db/sources/trigger/trigger.sql

mkdir -p $PWD/db/sources/table
mysqldump -h ${DB_HOST} -p${DB_PORT} -u${DB_USERNAME} -p${DB_PASSWORD} ${DB_NAME} --tables > $PWD/db/sources/table/table.sql

