#!/bin/bash

PSOF_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

source ${PSOF_DIR}/psof_config $PWD/psof.xml

echo Building project:${PSOF_XML_PROJECT_NAME}

case $PSOF_XML_PROJECT_APPLICATION_LANGUAGE in
    "java") 
    BUILD_CMD="mvn package -f app/pom.xml"
    $BUILD_CMD
    BUILD_CMD="docker build -t ${PSOF_XML_PROJECT_NAME}:latest -f cfg/Dockerfile ."
    $BUILD_CMD
    ;;
esac

exit 0;

